# netlify.toml

[build]
  command = "npm run build"  # Comando para construir tu aplicación
  publish = "frontend/dist"  # Directorio de archivos estáticos generados por el comando de construcción

[[redirects]]
  from = "/*"  # Redirigir todas las rutas a tu archivo HTML principal
  to = "/index.html"
  status = 200
